# travis.yml for testing radare2. Initially written in 2014, by jn__.
# Validate with http://yaml.travis-ci.org/.

language: c
compiler:
  - gcc
  - clang
  # TODO: add ASan (+LSan), MSan, TSan, ...

# Additional depencies like capstone are downloaded by the r2 makefiles.
install:
  - sudo apt-get install dc # GNU dc, used by r2r.
  - git clone `doc/repo REGRESSIONS`
  # This little hack will prevent the test names from being erased in the
  # travis logfile.
  - sed -i 's/\\r//' radare2-regressions/tests.sh

script:
  - ./configure   # TODO: Might enable some of the additional features.
  - make
  - sudo make install
  # "make tests" isn't run here, because it wouldn't cover everything anyway.
  - cd radare2-regressions
  - VERBOSE=1 make all
  - VERBOSE=1 make asm
  - VERBOSE=1 make formats
