name: "Pull Request Labeler"
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: paulfantom/periodic-labeler@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: ${{ github.repository }}
        LABEL_MAPPINGS_FILE: .github/labeler.yml
