name: Radare2 CI newshell

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [linux-meson-newshell]
        include:
          - name: linux-meson-newshell
            os: ubuntu-latest
            build_system: meson
            compiler: gcc
            meson_options: -Duse_treesitter=true
            newshell: newshell

    steps:
    - uses: actions/checkout@v2
    - name: Install meson and ninja
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools && pip3 install --user meson ninja
    - name: Checkout our Testsuite Binaries
      uses: actions/checkout@v2
      with:
          repository: radareorg/radare2-testbins
          path: test/bins
    - name: Build with Meson
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        meson ${{ matrix.meson_options }} --prefix=${HOME} build && ninja -C build
      env:
        CC: ${{ matrix.compiler }}
    - name: Install with meson
      run: |
        # Install the radare2
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        ninja -C build install
    - name: Run tests
      continue-on-error: true
      if: startswith(github.event.pull_request.head.ref, 'newshell-') || github.event_name == 'push'
      run: |
        # Running the test suite
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        export R2_CFG_NEWSHELL=1
        cd test
        make
