name: Radare2 Pre-Release checks

on:
  pull_requests:
    branches:
    - master
  push:
    branches:
    - 'pre-release*'
    - 'prerelease*'
    - 'release-*'

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [centos-6-build]
        include:
          - name: centos-6-build
            os: ubuntu-latest
            build_system: acr
            compiler: gcc
            container: centos:6
            capstone_release: 1

    steps:
    - uses: actions/checkout@v2
    - name: Install pkg-config with Homebrew
      if: matrix.os == 'macos-latest'
      run: brew install pkg-config
    - name: Install meson and ninja
      if: matrix.build_system == 'meson'
      run: sudo apt-get --assume-yes install python3-wheel python3-setuptools && pip3 install --user meson ninja
    - name: Install clang
      if: matrix.compiler == 'clang' && matrix.os == 'ubuntu-latest'
      run: sudo apt-get --assume-yes install clang
    - name: Install tools
      if: matrix.container == 'centos:6'
      run: sudo yum install -y patch unzip git gcc make
    - name: Configure with ACR and build
      if: matrix.build_system == 'acr'
      run: ./configure --prefix=${HOME} && make CS_RELEASE=${{ matrix.capstone_release }}
      env:
        CC: ${{ matrix.compiler }}
    - name: Build with Meson
      if: matrix.build_system == 'meson'
      run: |
        export PATH=${HOME}/.local/bin:${PATH}
        meson ${{ matrix.meson_options }} --prefix=${HOME} build && ninja -C build
      env:
        CC: ${{ matrix.compiler }}
    - name: Install with make
      if: matrix.build_system == 'acr'
      run: |
        # Install the radare2
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        make install
    - name: Install with meson
      if: matrix.build_system == 'meson'
      run: |
        # Install the radare2
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        ninja -C build install
    - name: Run tests
      run: |
        # Running the test suite
        export PATH=${HOME}/bin:${HOME}/.local/bin:${PATH}
        export LD_LIBRARY_PATH=${HOME}/lib/$(uname -m)-linux-gnu:${HOME}/lib:${HOME}/lib64:${LD_LIBRARY_PATH}
        export PKG_CONFIG_PATH=${HOME}/lib/pkgconfig:${HOME}/lib/$(uname -m)-linux-gnu/pkgconfig:${PKG_CONFIG_PATH}
        if [ "$NEWSHELL" == "true" ]; then
          export R2_CFG_NEWSHELL=1
        fi
        cd test
        radare2 -N -Qc 'e cfg.newshell' -
        make
      env:
        NEWSHELL: ${{ matrix.newshell }}
