name: Radare2 CI - static build

on:
  schedule:
    # “At 00:00 on every 7th day-of-week.”
    - cron:  '0 0 * * */7'
  pull_request:
    branches:
    - master

jobs:
  build:
    name: ubuntu-static-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout our Testsuite Binaries
      uses: actions/checkout@v2
      with:
          repository: radareorg/radare2-testbins
          path: test/bins
    - name: Install static
      run: |
        ./sys/static.sh
        sudo make symstall
    - name: Run tests
      run: |
        r2 -v
        r2r -v
        cd test
        make
